config/routes.rb
Rails.application.routes.draw do
  resources :gyms
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gym.rb
class Gym < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: %i(show edit update destroy)

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show; end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit; end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Workout created' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Workout updated' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to @gym, notice: 'Workout deleted' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gym
    @gym = Gym.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gym_params
    params.require(:gym).permit(:Date, :Workout)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= form_for(gym) do |f| %>
  <% if gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script type="text/javascript" language= "javascript">
    $( function() {
    $( "#date_input" ).datepicker({dateFormat: 'dd.mm.yy', defaultDate: new Date});
    $( "#date_input" ).datepicker("setDate", new Date );
   } );
  </script>

  <div class="input", align="center">
   <%= f.label :Date %>
   <%= f.text_field :Date, id: "date_input" %>


  <div class="field", align="center">
    <%= f.label :Workout %><br>
    <%= f.text_area :Workout, size:"30x10" %>
  </div>

  <div class="actions", align="center">
    <%= f.submit "Submit a  Workout" %>
  </div>
<% end %>

app/views/gyms/edit.html.erb
<h1>Editing Workout</h1>


<%= render 'form', gym: @gym %>

<p id ="show", align="center"><%= link_to 'Show', @gym, {:style => 'color:#FFF'}%> |
<%= link_to 'Back', gyms_path, {:style => 'color:#FFF'} %>

app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<body bgcolor="#D6EAF8">
  
</body>
<h1 align="center">Workouts</h1>

<table  cellpadding="10", align="center" >
  <thead>
    <tr >
      <th>Date</th>
      <th>Workout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody bgcolor= "#EBDEF0", align="center">
    <% @gyms.each do |gym| %>
      <tr align="center">
        <td><%= gym.Date %></td>
        <td><%= gym.Workout %></td>
        <td><%= link_to 'Show', gym %></td>
        <td><%= link_to 'Edit', edit_gym_path(gym) %></td>
        <td><%= link_to 'Destroy', gym, method: :delete, data: { confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p id ="new_work", align="center"><%= link_to 'New Workout', new_gym_path, {:style => 'color:#FFF'}%>

app/views/gyms/new.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
<body>
<h1>New Workout</h1>
<p id ="new_one" ><%= render 'form', gym: @gym %>
<p id ="new_two", align="center"><%= link_to 'Back', gyms_path, {:style => 'color:#FFF'} %>
</body>

app/views/gyms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @gym.Date %>
</p>

<p>
  <strong>Workout:</strong>
  <%= @gym.Workout %>
</p>

<%= link_to 'Edit', edit_gym_path(@gym), {:style => 'color:#FFF'} %> |
<%= link_to 'Show workouts', gyms_path,  {:style => 'color:#FFF'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>